image: docker:stable

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  TARGET_GAR: dynFoodBackEnd.gar

stages:
  - build
  - test
  - deploy

build-gar:
  stage: build
  image: "registry.gitlab.com/uk-fourjs-internal/docker-kubernetes/genero_docker_container:genero320_dbifx_gst_srv"
  script:
    - apt-get update
    - apt-get install -y make
    - export LANG=en_GB.utf8
    - update-locale en_GB.utf8
    - make gar || exit 1
    - ls distbin/${TARGET_GAR} && echo "OK" || exit 1
  artifacts:
    paths:
      - distbin/${TARGET_GAR}

test-gar:
  stage: test
  dependencies:
    - build-gar
  script:
    - echo "I guess I would do some fglrun sense checking here before I deploy it somewhere to a staging server?"

deploy-gar:
  stage: deploy
  script:
    - echo "If we got this far, lets deploy to a staging server!"